# Generated by Django 3.0.8 on 2020-07-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=5)),
                ('DOB', models.DateField()),
                ('MobileNo', models.IntegerField()),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Total_Price', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Item')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Register')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Register')),
            ],
        ),
    ]
